# Generated by Django 5.1.4 on 2025-01-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(unique=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('importance', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(choices=[('business', 'Business'), ('entertainment', 'Entertainment'), ('general', 'General'), ('health', 'Health'), ('science', 'Science'), ('sports', 'Sports'), ('technology', 'Technology')], max_length=50)),
            ],
        ),
    ]
