# Generated by Django 5.1.4 on 2025-01-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='preview_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='preview_image',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='preview_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
